// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=TipoTaco -json
type TipoTaco int64

const (
	TIPO_TACO_INVALID = iota
	TIPO_TACO_PASTOR
	TIPO_TACO_SUADERO
	TIPO_TACO_CAMPECHANO
	TIPO_TACO_BISTEC
	TIPO_TACO_LENGUA
	TIPO_TACO_TRIPA
	TIPO_TACO_CHORIZO
	TIPO_TACO_CANASTA
)

func (e TipoTaco) ToInt64() int64 {
	return int64(e)
}

func (e TipoTaco) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func TipoTacoFromString(in string) TipoTaco {
	switch in {
	case "invalid":
		return TIPO_TACO_INVALID
	case "pastor":
		return TIPO_TACO_PASTOR
	case "suadero":
		return TIPO_TACO_SUADERO
	case "campechano":
		return TIPO_TACO_CAMPECHANO
	case "bistec":
		return TIPO_TACO_BISTEC
	case "lengua":
		return TIPO_TACO_LENGUA
	case "tripa":
		return TIPO_TACO_TRIPA
	case "chorizo":
		return TIPO_TACO_CHORIZO
	case "canasta":
		return TIPO_TACO_CANASTA
	}
	return TIPO_TACO_INVALID
}

func TipoTacoFromPointerString(in *string) TipoTaco {
	if in == nil {
		return TIPO_TACO_INVALID
	}
	return TipoTacoFromString(*in)
}

func (e TipoTaco) String() string {
	switch e {
	case TIPO_TACO_INVALID:
		return "invalid"
	case TIPO_TACO_PASTOR:
		return "pastor"
	case TIPO_TACO_SUADERO:
		return "suadero"
	case TIPO_TACO_CAMPECHANO:
		return "campechano"
	case TIPO_TACO_BISTEC:
		return "bistec"
	case TIPO_TACO_LENGUA:
		return "lengua"
	case TIPO_TACO_TRIPA:
		return "tripa"
	case TIPO_TACO_CHORIZO:
		return "chorizo"
	case TIPO_TACO_CANASTA:
		return "canasta"
	}

	return "invalid"
}

func (e TipoTaco) StringPtr() *string {
	val := e.String()
	return &val
}

func TipoTacoSliceToJSON(in []TipoTaco) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling TipoTaco slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToTipoTacoSlice(in json.RawMessage) []TipoTaco {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling TipoTaco slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []TipoTaco{}
	for _, r := range res {
		finalRes = append(finalRes, TipoTaco(r))
	}
	return finalRes
}
