// Code generated by nuzur go-code-gen. DO NOT EDIT.

package enums

import (
	"encoding/json"
	"github.com/guregu/null/v6"
	"log"
)

//go:generate go run github.com/dmarkham/enumer -type=Veredicto -json
type Veredicto int64

const (
	VEREDICTO_INVALID = iota
	VEREDICTO_IMPERDIBLE
	VEREDICTO_BUENO
	VEREDICTO_PASABLE
	VEREDICTO_NUNCA_MAS
)

func (e Veredicto) ToInt64() int64 {
	return int64(e)
}

func (e Veredicto) ToNullInt() null.Int {
	return null.NewInt(int64(e), true)
}

func VeredictoFromString(in string) Veredicto {
	switch in {
	case "invalid":
		return VEREDICTO_INVALID
	case "imperdible":
		return VEREDICTO_IMPERDIBLE
	case "bueno":
		return VEREDICTO_BUENO
	case "pasable":
		return VEREDICTO_PASABLE
	case "nunca_mas":
		return VEREDICTO_NUNCA_MAS
	}
	return VEREDICTO_INVALID
}

func VeredictoFromPointerString(in *string) Veredicto {
	if in == nil {
		return VEREDICTO_INVALID
	}
	return VeredictoFromString(*in)
}

func (e Veredicto) String() string {
	switch e {
	case VEREDICTO_INVALID:
		return "invalid"
	case VEREDICTO_IMPERDIBLE:
		return "imperdible"
	case VEREDICTO_BUENO:
		return "bueno"
	case VEREDICTO_PASABLE:
		return "pasable"
	case VEREDICTO_NUNCA_MAS:
		return "nunca_mas"
	}

	return "invalid"
}

func (e Veredicto) StringPtr() *string {
	val := e.String()
	return &val
}

func VeredictoSliceToJSON(in []Veredicto) json.RawMessage {
	res := make([]int64, len(in))
	for i, e := range in {
		res[i] = int64(e)
	}
	jr, err := json.Marshal(res)
	if err != nil {
		log.Printf("error marshaling Veredicto slice to json: %v", err)
		// the empty ARRAY, not a zero-length RawMessage: the latter reaches the
		// driver as an empty string, which no JSON column accepts
		return json.RawMessage("[]")
	}
	return jr
}

func JSONToVeredictoSlice(in []byte) []Veredicto {
	res := []int64{}
	// an absent column (NULL / empty / JSON null) is not a decode failure
	if len(in) == 0 || string(in) == "null" {
		return nil
	}
	err := json.Unmarshal(in, &res)
	if err != nil {
		log.Printf("error unmarshaling Veredicto slice to int slice: %v", err)
		return nil
	}
	if len(res) == 0 {
		return nil
	}
	finalRes := []Veredicto{}
	for _, r := range res {
		finalRes = append(finalRes, Veredicto(r))
	}
	return finalRes
}
