// Code generated by nuzur go-code-gen. DO NOT EDIT.

package main

import (
	"go.uber.org/fx"
	"go.uber.org/zap"
	taqueriaconfig "taqueria/config"
	"taqueria/core"

	restserver "taqueria/rest/server"

	"taqueria/app"

	"taqueria/info"
)

func main() {
	fx.New(
		fx.Provide(
			zap.NewProduction,
			taqueriaconfig.New,
			core.New,

			app.ProvideCustomRoutes,
		),

		fx.Invoke(info.Register),

		fx.Invoke(app.RegisterWorkers),

		fx.Invoke(restserver.New),
	).Run()
}
