-- Code generated by nuzur go-code-gen. DO NOT EDIT.
CREATE TABLE IF NOT EXISTS `taqueria` (
    `id` CHAR(36) NOT NULL,
    `name` VARCHAR(120) NOT NULL,
    `colonia` VARCHAR(80) NOT NULL,
    `especialidad` INT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `instagram` VARCHAR(512),
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uq_taqueria_name` (`name`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `taco` (
    `id` CHAR(36) NOT NULL,
    `taqueria_uuid` CHAR(36) NOT NULL,
    `tipo` INT NOT NULL,
    `precio` DECIMAL(38,2) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `uq_taco_taqueria_tipo` (`taqueria_uuid`, `tipo`),
    CONSTRAINT `taqueria_has_tacos`
        FOREIGN KEY (`taqueria_uuid`)
        REFERENCES `taqueria` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `visita` (
    `id` CHAR(36) NOT NULL,
    `taqueria_uuid` CHAR(36) NOT NULL,
    `fecha` DATE NOT NULL,
    `veredicto` INT NOT NULL,
    `notas` VARCHAR(300),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_visita_taqueria_fecha` (`taqueria_uuid`, `fecha` DESC),
    CONSTRAINT `taqueria_has_visitas`
        FOREIGN KEY (`taqueria_uuid`)
        REFERENCES `taqueria` (`id`)
        ON DELETE CASCADE
) ENGINE = InnoDB;

