-- Code generated by nuzur go-code-gen. DO NOT EDIT.
-- name: DeleteTaqueria :execresult
DELETE FROM `taqueria`
WHERE
`id` = ?;

-- name: DeleteTaco :execresult
DELETE FROM `taco`
WHERE
`id` = ?;

-- name: DeleteVisita :execresult
DELETE FROM `visita`
WHERE
`id` = ?;

