-- Code generated by nuzur go-code-gen. DO NOT EDIT.
-- name: InsertTaqueria :execresult
INSERT INTO `taqueria`
(`id`,`name`,`colonia`,`especialidad`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?);

-- name: InsertTaco :execresult
INSERT INTO `taco`
(`id`,`taqueria_uuid`,`tipo`,`precio`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?);

-- name: InsertVisita :execresult
INSERT INTO `visita`
(`id`,`taqueria_uuid`,`fecha`,`veredicto`,`notas`,`created_at`,`updated_at`)
VALUES
(?,?,?,?,?,?,?);

