-- Code generated by nuzur go-code-gen. DO NOT EDIT.
-- name: FetchTaqueria :many
SELECT `id`,`name`,`colonia`,`especialidad`,`created_at`,`updated_at`,`instagram`
FROM `taqueria`;

-- name: FetchTaco :many
SELECT `id`,`taqueria_uuid`,`tipo`,`precio`,`created_at`,`updated_at`
FROM `taco`;

-- name: FetchVisita :many
SELECT `id`,`taqueria_uuid`,`fecha`,`veredicto`,`notas`,`created_at`,`updated_at`
FROM `visita`;

