-- Code generated by nuzur go-code-gen. DO NOT EDIT.


-- taqueria selects:
-- name: FetchTaqueriaByID :many
SELECT `id`,`name`,`colonia`,`especialidad`,`created_at`,`updated_at`,`instagram`
FROM `taqueria`
WHERE 
    `id` = ? ;

        
-- name: FetchTaqueriaByName :many
SELECT `id`,`name`,`colonia`,`especialidad`,`created_at`,`updated_at`,`instagram`
FROM `taqueria`
WHERE 
    `name` = ? 
LIMIT ?, ?;
        
-- name: FetchTaqueriaByIDForUpdate :many
SELECT `id`,`name`,`colonia`,`especialidad`,`created_at`,`updated_at`,`instagram`
FROM `taqueria`
WHERE 
    `id` = ? 
FOR UPDATE;
        




-- taco selects:
-- name: FetchTacoByID :many
SELECT `id`,`taqueria_uuid`,`tipo`,`precio`,`created_at`,`updated_at`
FROM `taco`
WHERE 
    `id` = ? ;

        
-- name: FetchTacoByTaqueriaUUIDAndTipo :many
SELECT `id`,`taqueria_uuid`,`tipo`,`precio`,`created_at`,`updated_at`
FROM `taco`
WHERE 
    `taqueria_uuid` = ? AND `tipo` = ? 
LIMIT ?, ?;
        
-- name: FetchTacoByIDForUpdate :many
SELECT `id`,`taqueria_uuid`,`tipo`,`precio`,`created_at`,`updated_at`
FROM `taco`
WHERE 
    `id` = ? 
FOR UPDATE;
        




-- visita selects:
-- name: FetchVisitaByID :many
SELECT `id`,`taqueria_uuid`,`fecha`,`veredicto`,`notas`,`created_at`,`updated_at`
FROM `visita`
WHERE 
    `id` = ? ;

        
-- name: FetchVisitaByTaqueriaUUID :many
SELECT `id`,`taqueria_uuid`,`fecha`,`veredicto`,`notas`,`created_at`,`updated_at`
FROM `visita`
WHERE 
    `taqueria_uuid` = ? 
LIMIT ?, ?;
        
-- name: FetchVisitaByIDForUpdate :many
SELECT `id`,`taqueria_uuid`,`fecha`,`veredicto`,`notas`,`created_at`,`updated_at`
FROM `visita`
WHERE 
    `id` = ? 
FOR UPDATE;
        


