-- Code generated by nuzur go-code-gen. DO NOT EDIT.
-- name: UpdateTaqueria :exec
UPDATE `taqueria`
SET
`name` = ?, `colonia` = ?, `especialidad` = ?, `created_at` = ?, `updated_at` = ?, `instagram` = ?
WHERE
`id` = ?;

-- name: UpdateTaco :exec
UPDATE `taco`
SET
`taqueria_uuid` = ?, `tipo` = ?, `precio` = ?, `created_at` = ?, `updated_at` = ?
WHERE
`id` = ?;

-- name: UpdateVisita :exec
UPDATE `visita`
SET
`taqueria_uuid` = ?, `fecha` = ?, `veredicto` = ?, `notas` = ?, `created_at` = ?, `updated_at` = ?
WHERE
`id` = ?;

