// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"net/http"
	"strings"
)

func AuthMiddleware(exceptions []string) func(http.Handler) http.Handler {

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			finalExceptions := []string{
				"/healthz",
				"/docs",
				"/openapi.yaml",

				// The public info page is served at the exact root path (the
				// handler 404s everything else), so except "/" alone — "/"+"/"
				// is "//", which no other request path prefixes.
				"/",
			}
			finalExceptions = append(exceptions, finalExceptions...)

			path := r.URL.Path
			isException := false
			for _, exc := range finalExceptions {
				if path == exc || strings.HasPrefix(path, exc+"/") {
					isException = true
					break
				}
			}

			if isException {
				next.ServeHTTP(w, r)
				return
			}

			next.ServeHTTP(w, r)
		})
	}
}
