// Code generated by nuzur go-code-gen. DO NOT EDIT.

package server

import (
	"context"
	"net"
	"net/http"

	"github.com/go-chi/chi/v5"
	"go.uber.org/config"
	"go.uber.org/fx"
	"go.uber.org/zap"

	"taqueria/core"
)

type Params struct {
	fx.In
	Lifecycle fx.Lifecycle
	Config    config.Provider
	Core      *core.Implementation
	Logger    *zap.Logger `optional:"true"`

	// Optional custom routes provided by the app package; mounted after the
	// generated CRUD routes so you can add or override endpoints.
	CustomRoutes CustomRoutesFn `optional:"true"`
}

// CustomRoutesFn registers custom REST routes on the server's chi router. The
// app package supplies one via fx; edit your routes in app/rest.go.
type CustomRoutesFn func(r chi.Router)

type handlers struct {
	core   *core.Implementation
	logger *zap.Logger
}

func New(params Params) *http.Server {
	logger := params.Logger
	if logger == nil {
		logger = zap.NewNop()
	}

	r := chi.NewRouter()

	r.Use(RequestID)
	r.Use(Recoverer)
	r.Use(Logger)
	r.Use(CORS)
	r.Use(ContentTypeJSON)

	h := &handlers{
		core:   params.Core,
		logger: logger,
	}

	mountRoutes(r, h)

	if params.CustomRoutes != nil {
		params.CustomRoutes(r)
	}

	port := params.Config.Get("ports.http").String()
	if port == "" {
		port = "8080"
	}
	addr := net.JoinHostPort("", port)

	srv := &http.Server{
		Addr:    addr,
		Handler: r,
	}

	params.Lifecycle.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			logger.Info("Starting REST HTTP server", zap.String("addr", addr))
			ln, err := net.Listen("tcp", srv.Addr)
			if err != nil {
				return err
			}
			go func() {
				if err := srv.Serve(ln); err != nil && err != http.ErrServerClosed {
					logger.Error("REST HTTP server error", zap.Error(err))
				}
			}()
			return nil
		},
		OnStop: func(ctx context.Context) error {
			logger.Info("Stopping REST HTTP server")
			return srv.Shutdown(ctx)
		},
	})

	return srv
}
