// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	"go.uber.org/zap"
	"taqueria/core/repository"
)

type ModuleParams struct {
	Repository *repository.Implementation
	Logger     *zap.Logger
}
