// Code generated by nuzur go-code-gen. DO NOT EDIT.

package core

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	_ "github.com/go-sql-driver/mysql"

	"go.uber.org/config"
	"go.uber.org/fx"
	"go.uber.org/zap"
	taqueriaconfig "taqueria/config"
	coretypes "taqueria/core/types"

	"taqueria/core/module/taqueria"

	"taqueria/core/module/taco"

	"taqueria/core/module/visita"

	"taqueria/core/repository"
)

type Implementation struct {
	db         *sql.DB
	repository *repository.Implementation
	logger     *zap.Logger

	taqueria taqueria.Module

	taco taco.Module

	visita visita.Module
}

type Params struct {
	fx.In
	Provider  config.Provider
	Lifecycle fx.Lifecycle
	Logger    *zap.Logger `optional:"true"`
}

func New(params Params) (*Implementation, error) {

	var dbs taqueriaconfig.DBs
	if err := params.Provider.Get("db").Populate(&dbs); err != nil {
		return nil, err
	}

	if len(dbs) == 0 {
		return nil, errors.New("db configuration not found")
	}

	dbconfig := dbs[0]
	db, err := sql.Open(dbconfig.Driver, dbconfig.Path())
	if err != nil {
		return nil, fmt.Errorf("error connecting to DB: %v", err)
	}
	db.SetConnMaxLifetime(0)
	db.SetMaxIdleConns(10)
	db.SetMaxOpenConns(0)
	repository := repository.New(db)

	logger := params.Logger
	if logger == nil {
		logger = zap.NewNop()
	}

	if params.Lifecycle != nil {
		params.Lifecycle.Append(fx.Hook{
			OnStart: func(ctx context.Context) error {
				// Warm the connection pool and fail fast with a clear error if the
				// database is unreachable or credentials/permissions are wrong,
				// instead of surfacing it later as a request-time timeout.
				pingCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
				defer cancel()
				if err := db.PingContext(pingCtx); err != nil {
					logger.Error("failed to connect to database on startup", zap.Error(err))
					return fmt.Errorf("error connecting to DB: %w", err)
				}
				logger.Info("connected to database")
				return nil
			},
			OnStop: func(ctx context.Context) error {
				db.Close()
				return nil
			},
		})
	}

	impl := &Implementation{
		db:         db,
		repository: repository,
		logger:     logger,
	}

	// Every module is built ONCE, here, and the accessors below just hand it
	// back. The accessors used to build their module lazily on a VALUE receiver,
	// so the assignment landed on a copy that was thrown away when the method
	// returned: every one of the (hundreds of) accessor calls in the transports
	// constructed a fresh module — with a fresh, empty 30s cache and its own
	// janitor goroutine — which is why the per-entity cache never served a hit
	// and WithSkipCache() meant nothing.
	//
	// Constructing eagerly rather than lazily on a POINTER receiver is
	// deliberate: the lazy branch would otherwise be a data race, since the
	// accessors are called concurrently from request handlers.

	impl.taqueria = taqueria.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	impl.taco = taco.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	impl.visita = visita.New(coretypes.ModuleParams{
		Repository: repository,
		Logger:     logger,
	})

	return impl, nil
}

func (i *Implementation) Destroy() {
	i.db.Close()
}

func (i *Implementation) DB() *sql.DB {
	return i.db
}

// Taqueria returns the process-wide taqueria module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) Taqueria() taqueria.Module {
	return i.taqueria
}

// Taco returns the process-wide taco module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) Taco() taco.Module {
	return i.taco
}

// Visita returns the process-wide visita module built in New.
// The receiver is a POINTER, like Destroy/DB above: a value receiver here would
// copy the struct on every call, which is how the previous lazy initialization
// came to be discarded.
func (i *Implementation) Visita() visita.Module {
	return i.visita
}
