// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taqueria

import (
	"context"
	"errors"

	"taqueria/core/module/taqueria/types"
)

func (m *module) Delete(
	ctx context.Context,
	req types.DeleteRequest,
	opts ...Option,
) error {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)

	existing, err := qtx.FetchTaqueriaByIDForUpdate(ctx,
		req.ID.String(),
	)
	if err != nil {

		return err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return err
	}

	_, err = qtx.DeleteTaqueria(
		ctx,
		req.ID.String(),
	)
	if err != nil {

		return err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return nil
}
