// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taqueria

import (
	"context"
	"fmt"

	"taqueria/core/module/taqueria/types"

	"errors"
	taqueriadb "taqueria/core/repository/gen"
)

func (m *module) FetchTaqueriaByName(
	ctx context.Context,
	req types.FetchTaqueriaByNameRequest,
	opts ...Option,
) (types.FetchTaqueriaByNameResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchTaqueriaByName:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchTaqueriaByNameResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchTaqueriaByName(
				ctx,
				taqueriadb.FetchTaqueriaByNameParams{
					Name: req.Name,

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchTaqueriaByNameResponse{}, err
			}
			return types.FetchTaqueriaByNameResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchTaqueriaByNameResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchTaqueriaByNameResponse{}, fetchErr
	}
	result := v.(types.FetchTaqueriaByNameResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
