// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taqueria

import (
	taqueriadb "taqueria/core/repository/gen"
	main_entity "taqueria/entity/taqueria"

	"taqueria/entity/mapper"

	"github.com/guregu/null/v6"
	"taqueria/enums"
)

func mapModelsToEntities(models []taqueriadb.Taqueria) []main_entity.Taqueria {
	result := []main_entity.Taqueria{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m taqueriadb.Taqueria) main_entity.Taqueria {
	return main_entity.Taqueria{
		ID:           mapper.StringToUUID(m.ID),
		Name:         m.Name,
		Colonia:      m.Colonia,
		Especialidad: enums.TipoTaco(m.Especialidad),
		CreatedAt:    m.CreatedAt,
		UpdatedAt:    m.UpdatedAt,
		Instagram:    null.NewString(m.Instagram.String, m.Instagram.Valid),
	}
}
