// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taqueria

import (
	"context"
	"errors"

	"taqueria/core/module/taqueria/types"
	taqueriadb "taqueria/core/repository/gen"

	"time"
)

func (m *module) Update(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {
	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	existing, err := qtx.FetchTaqueriaByIDForUpdate(ctx,
		req.Taqueria.ID.String(),
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if len(existing) == 0 {
		err := errors.New("entity not found")

		return types.UpsertResponse{}, err
	}

	// refresh server-managed timestamps that update on every write (updated_at)
	req.Taqueria.UpdatedAt = time.Now()

	// validate the merged entity against the schema's field type/type-config rules
	if err := req.Taqueria.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	params := mapUpsertRequestToUpdateParams(req)
	err = qtx.UpdateTaqueria(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildUpdateResponse(req), nil
}

func buildUpdateResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.Taqueria.ID,
	}
}

func mapUpsertRequestToUpdateParams(req types.UpsertRequest) taqueriadb.UpdateTaqueriaParams {
	return taqueriadb.UpdateTaqueriaParams{
		ID: req.Taqueria.ID.String(),

		Name: req.Taqueria.Name,

		Colonia: req.Taqueria.Colonia,

		Especialidad: req.Taqueria.Especialidad.ToInt64(),

		CreatedAt: req.Taqueria.CreatedAt,

		UpdatedAt: req.Taqueria.UpdatedAt,

		Instagram: req.Taqueria.Instagram,
	}
}
