// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "taqueria/entity/visita"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchVisitaByTaqueriaUUIDRequest struct {
	TaqueriaUUID uuid.UUID

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchVisitaByTaqueriaUUIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("taqueria_uuid", r.TaqueriaUUID.String())

	return nil
}

type FetchVisitaByTaqueriaUUIDResponse struct {
	Results []main_entity.Visita
}
