// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "taqueria/entity/visita"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchVisitaByIDRequest struct {
	ID uuid.UUID
}

func (r FetchVisitaByIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("id", r.ID.String())

	return nil
}

type FetchVisitaByIDResponse struct {
	Results []main_entity.Visita
}
