// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "taqueria/entity/visita"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Visita main_entity.Visita
}

type UpsertResponse struct {
	ID uuid.UUID
}
