// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "taqueria/entity/taqueria"

	"go.uber.org/zap/zapcore"
)

type FetchTaqueriaByNameRequest struct {
	Name string

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchTaqueriaByNameRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	return nil
}

type FetchTaqueriaByNameResponse struct {
	Results []main_entity.Taqueria
}
