// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "taqueria/entity/taqueria"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchTaqueriaByIDRequest struct {
	ID uuid.UUID
}

func (r FetchTaqueriaByIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("id", r.ID.String())

	return nil
}

type FetchTaqueriaByIDResponse struct {
	Results []main_entity.Taqueria
}
