// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "taqueria/entity/taqueria"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Taqueria main_entity.Taqueria
}

type UpsertResponse struct {
	ID uuid.UUID
}
