// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taco

import (
	"context"
	"database/sql"
	"taqueria/core/module/taco/types"
	repogen "taqueria/core/repository/gen"
	main_entity "taqueria/entity/taco"

	"go.uber.org/zap"
	"slices"
)

func (m *module) List(ctx context.Context,
	request types.ListRequest,
	opts ...Option) (types.ListResponse, error) {

	reqPlusOne := request
	reqPlusOne.PageSize = request.PageSize + 1

	query, err := m.repository.BuildListEntityQuery(
		ctx,
		reqPlusOne,
		main_entity.Taco{},
		false)
	if err != nil {

		return types.ListResponse{}, err
	}

	resolvedOpts := applyAllOptions(opts)
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it runs on the transaction and can neither be
	// served from the shared cache nor be collapsed into another caller's
	// in-flight query.
	var querier interface {
		QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	} = m.repository.DB
	if resolvedOpts.SQLTx != nil {
		querier = resolvedOpts.SQLTx
	}
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	// Keyed on the BUILT QUERY, which already encodes the filter, the ordering,
	// the projection and the page. Formatting the request instead put the
	// *filtering.Declarations POINTER in the key — a fresh allocation on every
	// request — so no two keys could ever match: the cache only grew, and the
	// singleflight group never collapsed anything.
	cacheKey := "ListTaco:" + query
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.ListResponse), nil
		}
	}

	list := func() (any, error) {
		var rows *sql.Rows
		rows, err = querier.QueryContext(ctx, query)
		if err != nil {

			m.logger.Error("error in executing query for ListTaco", zap.String("query", query), zap.Error(err))
			return types.ListResponse{}, err
		}
		defer rows.Close()
		var scanGetters []func(*repogen.Taco) any
		if len(request.GetIncludeFields()) > 0 {
			for _, f := range listFields {
				if slices.Contains(request.GetIncludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else if len(request.GetExcludeFields()) > 0 {
			for _, f := range listFields {
				if !slices.Contains(request.GetExcludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else {
			for _, f := range listFields {
				scanGetters = append(scanGetters, listFieldRegistry[f])
			}
		}

		var items []repogen.Taco
		for rows.Next() {
			var i repogen.Taco
			fields := make([]any, 0, len(scanGetters))
			for _, getter := range scanGetters {
				fields = append(fields, getter(&i))
			}
			if err := rows.Scan(fields...); err != nil {

				return types.ListResponse{}, err
			}
			items = append(items, i)
		}
		if err := rows.Close(); err != nil {

			return types.ListResponse{}, err
		}
		if err := rows.Err(); err != nil {

			return types.ListResponse{}, err
		}

		hasNextPage := false
		if len(items) > int(request.PageSize) {
			hasNextPage = true
			items = items[:request.PageSize]
		}

		return types.ListResponse{
			Taco:        mapModelsToEntities(items),
			HasNextPage: hasNextPage,
		}, nil
	}
	var v any
	var listErr error
	if skipShared {
		v, listErr = list()
	} else {
		v, listErr, _ = m.sg.Do(cacheKey, list)
	}
	if listErr != nil {
		return types.ListResponse{}, listErr
	}
	listResponse := v.(types.ListResponse)
	if !skipShared {
		m.cache.Set(cacheKey, listResponse, 0)
	}
	return listResponse, nil
}

var listFields = []string{

	"id",

	"taqueria_uuid",

	"tipo",

	"precio",

	"created_at",

	"updated_at",
}

var listFieldRegistry = map[string]func(*repogen.Taco) any{

	"id": func(i *repogen.Taco) any { return &i.ID },

	"taqueria_uuid": func(i *repogen.Taco) any { return &i.TaqueriaUUID },

	"tipo": func(i *repogen.Taco) any { return &i.Tipo },

	"precio": func(i *repogen.Taco) any { return &i.Precio },

	"created_at": func(i *repogen.Taco) any { return &i.CreatedAt },

	"updated_at": func(i *repogen.Taco) any { return &i.UpdatedAt },
}
