// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taco

import (
	taqueriadb "taqueria/core/repository/gen"
	main_entity "taqueria/entity/taco"

	"taqueria/entity/mapper"

	"taqueria/enums"
)

func mapModelsToEntities(models []taqueriadb.Taco) []main_entity.Taco {
	result := []main_entity.Taco{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m taqueriadb.Taco) main_entity.Taco {
	return main_entity.Taco{
		ID:           mapper.StringToUUID(m.ID),
		TaqueriaUUID: mapper.StringToUUID(m.TaqueriaUUID),
		Tipo:         enums.TipoTaco(m.Tipo),
		Precio:       m.Precio,
		CreatedAt:    m.CreatedAt,
		UpdatedAt:    m.UpdatedAt,
	}
}
