// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taco

import (
	"context"

	"taqueria/core/module/taco/types"
	taqueriadb "taqueria/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.Taco.ID == uuid.Nil {
		req.Taco.ID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.Taco.CreatedAt = time.Now()
	req.Taco.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.Taco.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertTaco(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.Taco.ID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) taqueriadb.InsertTacoParams {
	return taqueriadb.InsertTacoParams{
		ID: req.Taco.ID.String(),

		TaqueriaUUID: req.Taco.TaqueriaUUID.String(),

		Tipo: req.Taco.Tipo.ToInt64(),

		Precio: req.Taco.Precio,

		CreatedAt: req.Taco.CreatedAt,

		UpdatedAt: req.Taco.UpdatedAt,
	}
}
