// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "taqueria/entity/taco"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
	"taqueria/enums"
)

type FetchTacoByTaqueriaUUIDAndTipoRequest struct {
	TaqueriaUUID uuid.UUID
	Tipo         enums.TipoTaco

	Offset  int32
	Limit   int32
	OrderBy string
	Sort    string
}

func (r FetchTacoByTaqueriaUUIDAndTipoRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("taqueria_uuid", r.TaqueriaUUID.String())

	return nil
}

type FetchTacoByTaqueriaUUIDAndTipoResponse struct {
	Results []main_entity.Taco
}
