// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "taqueria/entity/taco"

	"github.com/gofrs/uuid"
	"go.uber.org/zap/zapcore"
)

type FetchTacoByIDRequest struct {
	ID uuid.UUID
}

func (r FetchTacoByIDRequest) MarshalLogObject(e zapcore.ObjectEncoder) error {

	e.AddString("id", r.ID.String())

	return nil
}

type FetchTacoByIDResponse struct {
	Results []main_entity.Taco
}
