// Code generated by nuzur go-code-gen. DO NOT EDIT.

package types

import (
	main_entity "taqueria/entity/taco"

	"github.com/gofrs/uuid"
)

type UpsertRequest struct {
	Taco main_entity.Taco
}

type UpsertResponse struct {
	ID uuid.UUID
}
