// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taco

import (
	entitytypes "taqueria/entity/types"
)

func (e Taco) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"id":            entitytypes.StringFieldType,
		"taqueria_uuid": entitytypes.StringFieldType,
		"tipo":          entitytypes.SingleEnumFieldType,
		"precio":        entitytypes.FloatFieldType,
		"created_at":    entitytypes.TimestampFieldType,
		"updated_at":    entitytypes.TimestampFieldType,
	}
}

func (e Taco) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "id")
	res = append(res, "taqueria_uuid")
	res = append(res, "tipo")
	res = append(res, "precio")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e Taco) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Taco) EntityIdentifier() string {
	return "taco"
}

func (e Taco) PrimaryKeyIdentifiers() []string {
	return []string{
		"id",
	}
}

func (e Taco) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
