// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taco

import (
	"taqueria/entity/validation"
)

// Validate checks this Taco against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Taco) Validate() error {
	c := validation.NewCollector()
	if e.ID.IsNil() {
		c.Require("taco.id")
	}
	if e.TaqueriaUUID.IsNil() {
		c.Require("taco.taqueria_uuid")
	}
	if e.Tipo.ToInt64() == 0 {
		c.Require("taco.tipo")
	} else {
		c.Field("taco.tipo", validation.EnumMember(e.Tipo.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6, 7, 8}, "tipo_taco"))

	}
	c.Field("taco.precio", validation.Float(e.Precio, false, 0, 0, false, false, false))

	return c.Result()
}
