// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taco

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"taqueria/enums"
	"time"

	"taqueria/entity/mapper"
)

type Taco struct {
	ID           uuid.UUID      `json:"id"`
	TaqueriaUUID uuid.UUID      `json:"taqueria_uuid"`
	Tipo         enums.TipoTaco `json:"tipo"`
	Precio       float64        `json:"precio"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (e Taco) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Taco) PrimaryKeyValues() []string {
	return []string{
		e.ID.String(),
	}
}

func TacoFromJSON(data json.RawMessage) Taco {
	entity := Taco{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error TacoFromJSON: %v\n", err2)
		}
	}
	return entity
}

func TacoSliceFromJSON(data json.RawMessage) []Taco {
	entity := []Taco{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Taco{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Taco{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error TacoSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Taco) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TacoToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func TacoToJSON(e Taco) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TacoToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// TacoSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func TacoSliceToJSON(e []Taco) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TacoSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
