// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taqueria

import (
	"taqueria/entity/validation"
)

// Validate checks this Taqueria against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Taqueria) Validate() error {
	c := validation.NewCollector()
	if e.ID.IsNil() {
		c.Require("taqueria.id")
	}
	if e.Name == "" {
		c.Require("taqueria.name")
	} else {
		c.Field("taqueria.name", validation.String(e.Name, 0, 120, ""))

	}
	if e.Colonia == "" {
		c.Require("taqueria.colonia")
	} else {
		c.Field("taqueria.colonia", validation.String(e.Colonia, 0, 80, ""))

	}
	if e.Especialidad.ToInt64() == 0 {
		c.Require("taqueria.especialidad")
	} else {
		c.Field("taqueria.especialidad", validation.EnumMember(e.Especialidad.ToInt64(), []int64{0, 1, 2, 3, 4, 5, 6, 7, 8}, "tipo_taco"))

	}

	return c.Result()
}
