// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taqueria

import (
	entitytypes "taqueria/entity/types"
)

func (e Taqueria) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"id":           entitytypes.StringFieldType,
		"name":         entitytypes.StringFieldType,
		"colonia":      entitytypes.StringFieldType,
		"especialidad": entitytypes.SingleEnumFieldType,
		"created_at":   entitytypes.TimestampFieldType,
		"updated_at":   entitytypes.TimestampFieldType,
		"instagram":    entitytypes.StringFieldType,
	}
}

func (e Taqueria) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "id")
	res = append(res, "name")
	res = append(res, "colonia")
	res = append(res, "especialidad")
	res = append(res, "created_at")
	res = append(res, "updated_at")
	res = append(res, "instagram")

	return res
}

func (e Taqueria) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Taqueria) EntityIdentifier() string {
	return "taqueria"
}

func (e Taqueria) PrimaryKeyIdentifiers() []string {
	return []string{
		"id",
	}
}

func (e Taqueria) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
