// Code generated by nuzur go-code-gen. DO NOT EDIT.

package taqueria

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"taqueria/enums"
	"time"

	"taqueria/entity/mapper"
)

type Taqueria struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Colonia      string         `json:"colonia"`
	Especialidad enums.TipoTaco `json:"especialidad"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (e Taqueria) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Taqueria) PrimaryKeyValues() []string {
	return []string{
		e.ID.String(),
	}
}

func TaqueriaFromJSON(data json.RawMessage) Taqueria {
	entity := Taqueria{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error TaqueriaFromJSON: %v\n", err2)
		}
	}
	return entity
}

func TaqueriaSliceFromJSON(data json.RawMessage) []Taqueria {
	entity := []Taqueria{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Taqueria{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Taqueria{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error TaqueriaSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Taqueria) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TaqueriaToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func TaqueriaToJSON(e Taqueria) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TaqueriaToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// TaqueriaSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func TaqueriaSliceToJSON(e []Taqueria) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error TaqueriaSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
