// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visita

import (
	"context"
	"fmt"

	"taqueria/core/module/visita/types"

	"errors"
	taqueriadb "taqueria/core/repository/gen"
)

func (m *module) FetchVisitaByTaqueriaUUID(
	ctx context.Context,
	req types.FetchVisitaByTaqueriaUUIDRequest,
	opts ...Option,
) (types.FetchVisitaByTaqueriaUUIDResponse, error) {

	resolvedOpts := applyAllOptions(opts)
	queries := m.repository.Queries
	if resolvedOpts.SQLTx != nil {
		queries = queries.WithTx(resolvedOpts.SQLTx)
	}
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it can neither be served from the shared cache nor
	// be collapsed into another caller's in-flight query.
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	cacheKey := fmt.Sprintf("FetchVisitaByTaqueriaUUID:%v", req)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.FetchVisitaByTaqueriaUUIDResponse), nil
		}
	}
	fetch := func() (any, error) {
		if req.OrderBy == "" {
			models, err := queries.FetchVisitaByTaqueriaUUID(
				ctx,
				taqueriadb.FetchVisitaByTaqueriaUUIDParams{
					TaqueriaUUID: req.TaqueriaUUID.String(),

					Offset: req.Offset,
					Limit:  req.Limit,
				},
			)

			if err != nil {

				return types.FetchVisitaByTaqueriaUUIDResponse{}, err
			}
			return types.FetchVisitaByTaqueriaUUIDResponse{
				Results: mapModelsToEntities(models),
			}, nil
		}

		err := errors.New("could not process request")

		return types.FetchVisitaByTaqueriaUUIDResponse{}, err
	} // end fetch
	var v any
	var fetchErr error
	if skipShared {
		v, fetchErr = fetch()
	} else {
		v, fetchErr, _ = m.sg.Do(cacheKey, fetch)
	}
	if fetchErr != nil {
		return types.FetchVisitaByTaqueriaUUIDResponse{}, fetchErr
	}
	result := v.(types.FetchVisitaByTaqueriaUUIDResponse)
	if !skipShared {
		m.cache.Set(cacheKey, result, 0)
	}
	return result, nil

}
