// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visita

import (
	"context"
	"database/sql"
	"taqueria/core/module/visita/types"
	repogen "taqueria/core/repository/gen"
	"taqueria/core/repository/list"
	main_entity "taqueria/entity/visita"

	"go.uber.org/zap"
	"slices"
)

func (m *module) List(ctx context.Context,
	request types.ListRequest,
	opts ...Option) (types.ListResponse, error) {

	reqPlusOne := request
	reqPlusOne.PageSize = request.PageSize + 1

	query, args, err := m.repository.BuildListEntityQuery(
		ctx,
		reqPlusOne,
		main_entity.Visita{},
		false)
	if err != nil {

		return types.ListResponse{}, err
	}

	resolvedOpts := applyAllOptions(opts)
	// A read inside a transaction must observe that transaction's own
	// uncommitted writes, so it runs on the transaction and can neither be
	// served from the shared cache nor be collapsed into another caller's
	// in-flight query.
	var querier interface {
		QueryContext(ctx context.Context, query string, args ...any) (*sql.Rows, error)
	} = m.repository.DB
	if resolvedOpts.SQLTx != nil {
		querier = resolvedOpts.SQLTx
	}
	skipShared := resolvedOpts.SkipCache || resolvedOpts.SQLTx != nil
	// Keyed on the BUILT QUERY *and its arguments*, which together encode the
	// filter, the ordering, the projection and the page. Formatting the request
	// instead put the *filtering.Declarations POINTER in the key — a fresh
	// allocation on every request — so no two keys could ever match: the cache
	// only grew, and the singleflight group never collapsed anything.
	//
	// The args are in the key because the filter VALUES are no longer in the
	// query text: two callers filtering on different values now build the SAME
	// text, so keying on the text alone would serve one of them the other's rows
	// — and the singleflight group shares this key, so it would not even take a
	// cache hit to do it.
	cacheKey := list.CacheKey("ListVisita", query, args)
	if !skipShared {
		if cached, found := m.cache.Get(cacheKey); found {
			return cached.(types.ListResponse), nil
		}
	}

	// Named runList, not list: the `list` identifier now refers to the repository
	// list package (CacheKey above), and a local of the same name would shadow it
	// for anything added below.
	runList := func() (any, error) {
		var rows *sql.Rows
		// The args MUST be passed: the built query carries placeholders where the
		// filter values used to be interpolated, so calling QueryContext without
		// them is a bind error, and interpolating them back into the text is the
		// injection this replaced.
		rows, err = querier.QueryContext(ctx, query, args...)
		if err != nil {

			// The query text is logged; the ARGS are not, only their count. The
			// values are caller data, and they are exactly what used to end up in
			// the text — logging them would put them back in every log sink.
			m.logger.Error("error in executing query for ListVisita", zap.String("query", query), zap.Int("args", len(args)), zap.Error(err))
			return types.ListResponse{}, err
		}
		defer rows.Close()
		var scanGetters []func(*repogen.Visita) any
		if len(request.GetIncludeFields()) > 0 {
			for _, f := range listFields {
				if slices.Contains(request.GetIncludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else if len(request.GetExcludeFields()) > 0 {
			for _, f := range listFields {
				if !slices.Contains(request.GetExcludeFields(), f) {
					scanGetters = append(scanGetters, listFieldRegistry[f])
				}
			}
		} else {
			for _, f := range listFields {
				scanGetters = append(scanGetters, listFieldRegistry[f])
			}
		}

		var items []repogen.Visita
		for rows.Next() {
			var i repogen.Visita
			fields := make([]any, 0, len(scanGetters))
			for _, getter := range scanGetters {
				fields = append(fields, getter(&i))
			}
			if err := rows.Scan(fields...); err != nil {

				return types.ListResponse{}, err
			}
			items = append(items, i)
		}
		if err := rows.Close(); err != nil {

			return types.ListResponse{}, err
		}
		if err := rows.Err(); err != nil {

			return types.ListResponse{}, err
		}

		hasNextPage := false
		if len(items) > int(request.PageSize) {
			hasNextPage = true
			items = items[:request.PageSize]
		}

		return types.ListResponse{
			Visita:      mapModelsToEntities(items),
			HasNextPage: hasNextPage,
		}, nil
	}
	var v any
	var listErr error
	if skipShared {
		v, listErr = runList()
	} else {
		v, listErr, _ = m.sg.Do(cacheKey, runList)
	}
	if listErr != nil {
		return types.ListResponse{}, listErr
	}
	listResponse := v.(types.ListResponse)
	if !skipShared {
		m.cache.Set(cacheKey, listResponse, 0)
	}
	return listResponse, nil
}

var listFields = []string{

	"id",

	"taqueria_uuid",

	"fecha",

	"veredicto",

	"notas",

	"created_at",

	"updated_at",
}

var listFieldRegistry = map[string]func(*repogen.Visita) any{

	"id": func(i *repogen.Visita) any { return &i.ID },

	"taqueria_uuid": func(i *repogen.Visita) any { return &i.TaqueriaUUID },

	"fecha": func(i *repogen.Visita) any { return &i.Fecha },

	"veredicto": func(i *repogen.Visita) any { return &i.Veredicto },

	"notas": func(i *repogen.Visita) any { return &i.Notas },

	"created_at": func(i *repogen.Visita) any { return &i.CreatedAt },

	"updated_at": func(i *repogen.Visita) any { return &i.UpdatedAt },
}
