// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visita

import (
	taqueriadb "taqueria/core/repository/gen"
	main_entity "taqueria/entity/visita"

	"taqueria/entity/mapper"

	"github.com/guregu/null/v6"
	"taqueria/enums"
)

func mapModelsToEntities(models []taqueriadb.Visita) []main_entity.Visita {
	result := []main_entity.Visita{}
	for _, p := range models {
		result = append(result, mapModelToEntity(p))
	}
	return result
}

func mapModelToEntity(m taqueriadb.Visita) main_entity.Visita {
	return main_entity.Visita{
		ID:           mapper.StringToUUID(m.ID),
		TaqueriaUUID: mapper.StringToUUID(m.TaqueriaUUID),
		Fecha:        m.Fecha,
		Veredicto:    enums.Veredicto(m.Veredicto),
		Notas:        null.NewString(m.Notas.String, m.Notas.Valid),
		CreatedAt:    m.CreatedAt,
		UpdatedAt:    m.UpdatedAt,
	}
}
