// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visita

import (
	"context"

	"taqueria/core/module/visita/types"
	taqueriadb "taqueria/core/repository/gen"

	"github.com/gofrs/uuid"

	"time"
)

func (m *module) Insert(
	ctx context.Context,
	req types.UpsertRequest,
	opts ...Option,
) (types.UpsertResponse, error) {

	// auto-generate primary-key UUIDs for new records when not supplied by the caller
	if req.Visita.ID == uuid.Nil {
		req.Visita.ID = uuid.Must(uuid.NewV4())
	}

	// server-managed timestamps (generated created_at/updated_at)
	req.Visita.CreatedAt = time.Now()
	req.Visita.UpdatedAt = time.Now()

	// validate the new record against the schema's field type/type-config rules
	if err := req.Visita.Validate(); err != nil {

		return types.UpsertResponse{}, err
	}

	optConfig := applyAllOptions(opts)

	tx := optConfig.SQLTx
	createdTx := false
	if tx == nil {
		ntx, err := m.repository.DB.Begin()
		if err != nil {
			return types.UpsertResponse{}, err
		}
		tx = ntx
		defer tx.Rollback()
		createdTx = true
	}

	qtx := m.repository.Queries.WithTx(tx)
	params := mapUpsertRequestToInsertParams(req)

	_, err := qtx.InsertVisita(
		ctx,
		params,
	)
	if err != nil {

		return types.UpsertResponse{}, err
	}

	if createdTx {
		err := tx.Commit()
		if err != nil {

			return types.UpsertResponse{}, err
		}
	}

	// The rows this module caches have changed, so everything it holds is
	// suspect: drop it rather than answer a later read from a snapshot that
	// predates this write. The cache is per entity, so this discards only this
	// entity's reads. (It is a no-op while a caller-supplied transaction is
	// still open — those reads bypass the cache anyway.)
	m.cache.Flush()

	return buildInsertResponse(req), nil
}

func buildInsertResponse(req types.UpsertRequest) types.UpsertResponse {
	return types.UpsertResponse{

		ID: req.Visita.ID,
	}
}

func mapUpsertRequestToInsertParams(req types.UpsertRequest) taqueriadb.InsertVisitaParams {
	return taqueriadb.InsertVisitaParams{
		ID: req.Visita.ID.String(),

		TaqueriaUUID: req.Visita.TaqueriaUUID.String(),

		Fecha: req.Visita.Fecha,

		Veredicto: req.Visita.Veredicto.ToInt64(),

		Notas: req.Visita.Notas,

		CreatedAt: req.Visita.CreatedAt,

		UpdatedAt: req.Visita.UpdatedAt,
	}
}
