// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visita

import (
	"context"
	gocache "github.com/patrickmn/go-cache"
	"go.uber.org/zap"
	"golang.org/x/sync/singleflight"
	"sync"
	"taqueria/core/module/visita/types"
	"taqueria/core/repository"
	coretypes "taqueria/core/types"
	"time"
)

type Module interface {
	FetchVisitaByID(ctx context.Context, req types.FetchVisitaByIDRequest, opts ...Option) (types.FetchVisitaByIDResponse, error)
	FetchVisitaByTaqueriaUUID(ctx context.Context, req types.FetchVisitaByTaqueriaUUIDRequest, opts ...Option) (types.FetchVisitaByTaqueriaUUIDResponse, error)

	List(ctx context.Context, req types.ListRequest, opts ...Option) (types.ListResponse, error)

	Upsert(ctx context.Context, req types.UpsertRequest, opts ...Option) (types.UpsertResponse, error)
	Insert(ctx context.Context, req types.UpsertRequest, opts ...Option) (types.UpsertResponse, error)
	Update(ctx context.Context, req types.UpsertRequest, opts ...Option) (types.UpsertResponse, error)
	Delete(ctx context.Context, req types.DeleteRequest, opts ...Option) error
}

type module struct {
	mu         sync.Mutex
	sg         singleflight.Group
	cache      *gocache.Cache
	repository *repository.Implementation
	logger     *zap.Logger
}

func New(params coretypes.ModuleParams) Module {
	return &module{
		repository: params.Repository,
		logger:     params.Logger,
		cache:      gocache.New(30*time.Second, 5*time.Minute),
	}
}
