// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visita

import (
	entitytypes "taqueria/entity/types"
)

func (e Visita) FieldIdentifierToTypeMap() map[string]entitytypes.FieldType {
	return map[string]entitytypes.FieldType{
		"id":            entitytypes.StringFieldType,
		"taqueria_uuid": entitytypes.StringFieldType,
		"fecha":         entitytypes.TimestampFieldType,
		"veredicto":     entitytypes.SingleEnumFieldType,
		"notas":         entitytypes.StringFieldType,
		"created_at":    entitytypes.TimestampFieldType,
		"updated_at":    entitytypes.TimestampFieldType,
	}
}

func (e Visita) OrderedFieldIdentifiers() []string {
	res := []string{}
	res = append(res, "id")
	res = append(res, "taqueria_uuid")
	res = append(res, "fecha")
	res = append(res, "veredicto")
	res = append(res, "notas")
	res = append(res, "created_at")
	res = append(res, "updated_at")

	return res
}

func (e Visita) DependantFieldIdentifierToTypeMap() map[string]map[string]entitytypes.FieldType {
	res := make(map[string]map[string]entitytypes.FieldType)

	return res
}

func (e Visita) EntityIdentifier() string {
	return "visita"
}

func (e Visita) PrimaryKeyIdentifiers() []string {
	return []string{
		"id",
	}
}

func (e Visita) ArrayFieldIdentifierToType() map[string]entitytypes.FieldType {
	res := make(map[string]entitytypes.FieldType)

	return res
}
