// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visita

import (
	"encoding/json"
	"log"

	"github.com/gofrs/uuid"
	"github.com/guregu/null/v6"
	"taqueria/enums"
	"time"

	"taqueria/entity/mapper"
)

type Visita struct {
	ID           uuid.UUID       `json:"id"`
	TaqueriaUUID uuid.UUID       `json:"taqueria_uuid"`
	Fecha        time.Time       `json:"fecha"`
	Veredicto    enums.Veredicto `json:"veredicto"`
	Notas        null.String     `json:"notas"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (e Visita) String() string {
	res, _ := json.Marshal(e)
	return string(res)
}

func (e Visita) PrimaryKeyValues() []string {
	return []string{
		e.ID.String(),
	}
}

func VisitaFromJSON(data json.RawMessage) Visita {
	entity := Visita{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		if err2 := mapper.FlexibleUnmarshal(data, &entity); err2 != nil {
			log.Printf("flexible unmarshal error VisitaFromJSON: %v\n", err2)
		}
	}
	return entity
}

func VisitaSliceFromJSON(data json.RawMessage) []Visita {
	entity := []Visita{}
	if data == nil {
		return entity
	}
	if len(data) == 0 {
		return entity
	}

	if err := json.Unmarshal(data, &entity); err != nil {
		entity = []Visita{}
		var rawSlice []json.RawMessage
		if err2 := json.Unmarshal(data, &rawSlice); err2 == nil {
			for _, raw := range rawSlice {
				item := Visita{}
				if err3 := mapper.FlexibleUnmarshal(raw, &item); err3 != nil {
					log.Printf("flexible unmarshal error VisitaSliceFromJSON item: %v\n", err3)
				}
				entity = append(entity, item)
			}
		}
	}
	return entity
}

func (e Visita) ToJSON() json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error VisitaToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

func VisitaToJSON(e Visita) json.RawMessage {
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error VisitaToJSON: %v\n", err)
		return json.RawMessage("null")
	}
	return res
}

// VisitaSliceToJSON serializes a ONE_TO_MANY embed for its JSON column.
// An absent embed is the EMPTY ARRAY, never a zero-length json.RawMessage: a
// zero-length value reaches the driver as the empty string, which is not valid
// JSON, so a create that simply omitted an optional array embed was rejected by
// the database ("invalid input syntax for type json", MySQL error 3140) and
// surfaced as a 500. "[]" is also exactly what an explicit `"field": []` stores,
// so the omitted and the explicitly-empty request round-trip to the same value.
func VisitaSliceToJSON(e []Visita) json.RawMessage {
	if e == nil {
		return json.RawMessage("[]")
	}
	res, err := json.Marshal(e)
	if err != nil {
		log.Printf("marshal error VisitaSliceToJSON: %v\n", err)
		return json.RawMessage("[]")
	}
	return res
}
