// Code generated by nuzur go-code-gen. DO NOT EDIT.

package visita

import (
	"taqueria/entity/validation"
)

// Validate checks this Visita against the schema's field type and
// type-config rules, aggregating every problem into a single *validation.Error.
// It mirrors the change-request data validation enforced in
// product/module/datavalidation, so data written through this API is held to
// the same rules. Generated by go-code-gen — do not edit.
func (e Visita) Validate() error {
	c := validation.NewCollector()
	if e.ID.IsNil() {
		c.Require("visita.id")
	}
	if e.TaqueriaUUID.IsNil() {
		c.Require("visita.taqueria_uuid")
	}
	if e.Fecha.IsZero() {
		c.Require("visita.fecha")
	}
	if e.Veredicto.ToInt64() == 0 {
		c.Require("visita.veredicto")
	} else {
		c.Field("visita.veredicto", validation.EnumMember(e.Veredicto.ToInt64(), []int64{0, 1, 2, 3, 4}, "veredicto"))

	}
	if e.Notas.Valid && e.Notas.String != "" {
		c.Field("visita.notas", validation.String(e.Notas.String, 0, 300, ""))

	}

	return c.Result()
}
