// Code generated by nuzur go-code-gen. DO NOT EDIT.

package repository

import (
	"context"

	"database/sql"

	taqueriadb "taqueria/core/repository/gen"
	"taqueria/core/repository/list"
)

type Implementation struct {
	Queries *taqueriadb.Queries
	DB      *sql.DB
	List    *list.Implementation
}

func New(db *sql.DB) *Implementation {
	queries := taqueriadb.New(db)
	return &Implementation{
		Queries: queries,
		DB:      db,
		List:    list.New(),
	}
}

func (i *Implementation) BuildListEntityQuery(ctx context.Context, request list.ListRequest, entity list.ListEntity, onlyCount bool) (string, error) {
	return i.List.BuildListEntityQuery(ctx, request, entity, onlyCount)
}
